import {
    animation_duration,
    chat,
    cleanUpMessage,
    event_types,
    eventSource,
    Generate,
    getGeneratingApi,
    is_send_press,
    isStreamingEnabled,
    substituteParamsExtended,
} from '../script.js';
import { debounce, delay, getStringHash } from './utils.js';
import { decodeTextTokens, getTokenizerBestMatch } from './tokenizers.js';
import { power_user } from './power-user.js';
import { callGenericPopup, POPUP_TYPE } from './popup.js';
import { t } from './i18n.js';

const TINTS = 4;
const MAX_MESSAGE_LOGPROBS = 100;
const REROLL_BUTTON = document.getElementById('logprobsReroll');

/**
 * Tuple of a candidate token and its logarithm of probability of being chosen
 * @typedef {[string, number]} Candidate - (token, logprob)
 */



/**
 * Logprob data for a single message
 * @typedef {object} MessageLogprobData
 * @property {number} created - timestamp of when the message was generated
 * @property {number} hash - hash of the message object
 * @property {number} messageId - ID of the source message
 * @property {number} swipeId - ID of the source swipe on the source message
 * @property {string} api - API used to generate the message
 * @property {TokenLogprobs[]} messageLogprobs Logprob data for each token, by
 * its index in the message
 * @property {string | null} continueFrom - the 'continue' prefix used to
 * generate the message, if any
 */

/**
 * Logprob data for a single token
 * @typedef {object} TokenLogprobs
 * @property {string} token - A token generated by the model
 * @property {Candidate[]} topLogprobs - Array of top candidate tokens
 */

/**
 * State object for Token Probabilities
 * @typedef {object} LogprobsState
 * @property {?TokenLogprobs} selectedTokenLogprobs Log probabilities for
 * currently-selected token.
 * @property {Map<number, MessageLogprobData>} messageLogprobs Log probabilities for
 * each message, keyed by message hash.
 */

/**
 * @type {LogprobsState} state
 */
const state = {
    selectedTokenLogprobs: null,
    messageLogprobs: new Map(),
};

/**
 * Renders the Token Probabilities UI and all subviews with the active message's
 * logprobs data. If the message has no token logprobs, a message is displayed.
 */
function renderAlternativeTokensView() {
    const view = document.getElementById('logprobs_generation_output');
    if (!view || view.style.display === 'none') {
        return;
    }
    if (view) view.innerHTML = '';
    state.selectedTokenLogprobs = null;
    renderTopLogprobs();

    const { messageLogprobs, continueFrom } = getActiveMessageLogprobData() || {};
    const usingSmoothStreaming = isStreamingEnabled() && power_user.smooth_streaming;
    if (!messageLogprobs?.length || usingSmoothStreaming) {
        const emptyState = document.createElement('div');
        const noTokensMsg = !power_user.request_token_probabilities
            ? '<span>Enable <b>Request token probabilities</b> in the User Settings menu to use this feature.</span>'
            : usingSmoothStreaming
                ? t`Token probabilities are not available when using Smooth Streaming.`
                : is_send_press
                    ? t`Generation in progress...`
                    : t`No token probabilities available for the current message.`;
        emptyState.innerHTML = noTokensMsg;
        emptyState.classList.add('logprobs_empty_state');
        view?.appendChild(emptyState);
        return;
    }

    const prefix = continueFrom || '';
    // @ts-expect-error TS(7034) FIXME: Variable 'tokenSpans' implicitly has type 'any[]' ... Remove this comment to see the full error message
    const tokenSpans = [];
    if (REROLL_BUTTON) {
        REROLL_BUTTON.style.display = prefix ? '' : 'none';
    }

    if (prefix) {
        if (REROLL_BUTTON) {
            // @ts-expect-error TS(2339) FIXME: Property '_rerollHandler' does not exist on type '... Remove this comment to see the full error message
            if (REROLL_BUTTON._rerollHandler) {
                // @ts-expect-error TS(2339) FIXME: Property '_rerollHandler' does not exist on type '... Remove this comment to see the full error message
                REROLL_BUTTON.removeEventListener('click', REROLL_BUTTON._rerollHandler);
            }
            // @ts-expect-error TS(2339) FIXME: Property '_rerollHandler' does not exist on type '... Remove this comment to see the full error message
            REROLL_BUTTON._rerollHandler = () => onPrefixClicked(prefix.length);
            // @ts-expect-error TS(2339) FIXME: Property '_rerollHandler' does not exist on type '... Remove this comment to see the full error message
            REROLL_BUTTON.addEventListener('click', REROLL_BUTTON._rerollHandler);
        }

        let cumulativeOffset = 0;
        const words = prefix.split(/\s+/);
        const delimiters = prefix.match(/\s+/g) || [];

        // @ts-expect-error TS(7006) FIXME: Parameter 'word' implicitly has an 'any' type.
        words.forEach((word, i) => {
            const span = document.createElement('span');
            span.textContent = `${word} `;

            span.classList.add('logprobs_output_prefix');
            span.setAttribute('title', t`Reroll from this point`);

            const offset = cumulativeOffset;
            // @ts-expect-error TS(2345) FIXME: Argument of type 'number' is not assignable to par... Remove this comment to see the full error message
            span.addEventListener('click', () => onPrefixClicked(offset));
            addKeyboardProps(span);

            tokenSpans.push(span);
            tokenSpans.push(delimiters[i]?.includes('\n')
                ? document.createElement('br')
                : document.createTextNode(delimiters[i] || ' '),
            );

            cumulativeOffset += word.length + (delimiters[i]?.length || 0);
        });
    }

    // @ts-expect-error TS(7006) FIXME: Parameter 'tokenData' implicitly has an 'any' type... Remove this comment to see the full error message
    messageLogprobs.forEach((tokenData, i) => {
        const { token } = tokenData;
        const span = document.createElement('span');
        const text = toVisibleWhitespace(token);
        span.textContent = text;
        span.classList.add('logprobs_output_token');
        span.classList.add('logprobs_tint_' + (i % TINTS));
        span.addEventListener('click', () => onSelectedTokenChanged(tokenData, span));
        addKeyboardProps(span);
        tokenSpans.push(...withVirtualWhitespace(token, span));
    });

    // @ts-expect-error TS(7005) FIXME: Variable 'tokenSpans' implicitly has an 'any[]' ty... Remove this comment to see the full error message
    view?.append(...tokenSpans);

    // scroll past long prior context
    if (prefix) {
        const element = view.querySelector('.logprobs_output_token');
        if (element) {
            // @ts-expect-error TS(2531) FIXME: Object is possibly 'null'.
            const scrollOffset = element.getBoundingClientRect().top - element.parentElement.getBoundingClientRect().top;
            // @ts-expect-error TS(2531) FIXME: Object is possibly 'null'.
            element.parentElement.scrollTop = scrollOffset;
        }
    }
}

/**
 *
 * @param element
 */
// @ts-expect-error TS(7006) FIXME: Parameter 'element' implicitly has an 'any' type.
function addKeyboardProps(element) {
    element.setAttribute('role', 'button');
    element.setAttribute('tabindex', '0');
    // @ts-expect-error TS(7006) FIXME: Parameter 'e' implicitly has an 'any' type.
    element.addEventListener('keydown', function (e) {
        if (e.key === 'Enter' || e.key === ' ') {
            element.click();
        }
    });
}

/**
 * renderTopLogprobs renders the top logprobs subview with the currently
 * selected token highlighted. If no token is selected, the subview is hidden.
 *
 * Callers:
 * - renderAlternativeTokensView, to render the entire view
 * - onSelectedTokenChanged, to update the view when a token is selected
 */
function renderTopLogprobs() {
    const hint = document.getElementById('logprobs_top_logprobs_hint');
    if (hint) hint.style.display = 'none';
    const view = document.querySelector('.logprobs_candidate_list');
    if (view) view.innerHTML = '';

    if (!state.selectedTokenLogprobs) {
        return;
    }

    const { token: selectedToken, topLogprobs } = state.selectedTokenLogprobs;

    let sum = 0;
    const nodes = [];
    const candidates = topLogprobs
        // @ts-expect-error TS(2339) FIXME: Property 'sort' does not exist on type 'never'.
        .sort(([, logA], [, logB]) => logB - logA)
        // @ts-expect-error TS(7031) FIXME: Binding element 'text' implicitly has an 'any' typ... Remove this comment to see the full error message
        .map(([text, log]) => {
            if (log <= 0) {
                const probability = Math.exp(log);
                sum += probability;
                return [text, probability, log];
            } else {
                return [text, log, null];
            }
        });
    candidates.push(['<others>', 1 - sum, 0]);

    let matched = false;
    for (const [token, probability, log] of candidates) {
        const container = document.createElement('button');
        container.className = 'flex-container flexFlowColumn logprobs_top_candidate';
        const tokenNormalized = String(token).replace(/^[▁Ġ]/g, ' ');

        if (token === selectedToken || tokenNormalized === selectedToken) {
            matched = true;
            container.classList.add('selected');
        }

        const tokenText = document.createElement('span');
        tokenText.textContent = `${toVisibleWhitespace(token.toString())}`;
        const percentText = document.createElement('span');
        percentText.textContent = `${(+probability * 100).toFixed(2)}%`;
        container.append(tokenText, percentText);
        if (log) {
            container.setAttribute('title', `logarithm: ${log}`);
        }
        addKeyboardProps(container);
        if (token !== '<others>') {
            container.addEventListener('click', () => onAlternativeClicked(state.selectedTokenLogprobs, token.toString()));
        } else {
            container.disabled = true;
        }
        nodes.push(container);
    }

    // Highlight the <others> node if the selected token was not included in the
    // top logprobs
    if (!matched) {
        // @ts-expect-error TS(2532) FIXME: Object is possibly 'undefined'.
        nodes[nodes.length - 1].style.backgroundColor = 'rgba(255, 0, 0, 0.1)';
    }

    view?.append(...nodes);
}

/**
 * User clicks on a token in the token output view. It updates the selected token state
 * and re-renders the top logprobs view, or deselects the token if it was already selected.
 * @param {TokenLogprobs} logprobs - logprob data for the selected token
 * @param {HTMLElement} span - target span node that was clicked
 */
// @ts-expect-error TS(7006) FIXME: Parameter 'logprobs' implicitly has an 'any' type.
function onSelectedTokenChanged(logprobs, span) {
    document.querySelectorAll('.logprobs_output_token.selected').forEach((el) => el.classList.remove('selected'));
    if (state.selectedTokenLogprobs === logprobs) {
        state.selectedTokenLogprobs = null;
    } else {
        state.selectedTokenLogprobs = logprobs;
        span.classList.add('selected');
    }
    renderTopLogprobs();
}

/**
 * onAlternativeClicked is called when the user clicks on an alternative token
 * in the top logprobs view. It will create a new swipe message and prefill it
 * with all text up to the selected token, followed by the chosen alternative.
 * Then it requests a `continue` completion from the model with the new prompt.
 * @param {TokenLogprobs} tokenLogprobs - logprob data for selected alternative
 * @param {string} alternative - selected alternative token's text
 */
// @ts-expect-error TS(7006) FIXME: Parameter 'tokenLogprobs' implicitly has an 'any' ... Remove this comment to see the full error message
function onAlternativeClicked(tokenLogprobs, alternative) {
    if (!checkGenerateReady()) {
        return;
    }

    if (getGeneratingApi() === 'openai') {
        const title = t`Feature unavailable`;
        const message = t`Due to API limitations, rerolling a token is not supported with OpenAI. Try switching to a different API.`;
        const content = `<h3>${title}</h3><p>${message}</p>`;
        return callGenericPopup(content, POPUP_TYPE.TEXT);
    }

    const { messageLogprobs, continueFrom } = getActiveMessageLogprobData();
    // @ts-expect-error TS(7006) FIXME: Parameter 'x' implicitly has an 'any' type.
    const replaceIndex = messageLogprobs.findIndex(x => x === tokenLogprobs);

    // @ts-expect-error TS(7031) FIXME: Binding element 'token' implicitly has an 'any' ty... Remove this comment to see the full error message
    const tokens = messageLogprobs.slice(0, replaceIndex + 1).map(({ token }) => token);
    tokens[replaceIndex] = String(alternative).replace(/^[▁Ġ]/g, ' ').replace(/Ċ/g, '\n');

    const prefix = continueFrom || '';
    const prompt = prefix + tokens.join('');
    addGeneration(prompt);
}

/**
 * User clicks on the reroll button in the token output view, or on a word in the
 * prefix. Retrieve the prefix for the current message and truncate it at the
 * offset for the selected word. Then request a `continue` completion from the
 * model with the new prompt.
 *
 * If no offset is provided, the entire prefix will be rerolled.
 * @param {number} offset - index of the token in the prefix to reroll from
 * @returns {void}
 * @param offset
 */
function onPrefixClicked(offset = undefined) {
    if (!checkGenerateReady()) {
        return;
    }

    const { continueFrom } = getActiveMessageLogprobData() || {};
    const prefix = continueFrom ? continueFrom.substring(0, offset) : '';
    addGeneration(prefix);
}

/**
 *
 */
function checkGenerateReady() {
    if (is_send_press) {
        // @ts-expect-error TS(2304) FIXME: Cannot find name 'toastr'.
        toastr.warning('Please wait for the current generation to complete.');
        return false;
    }
    return true;
}

/**
 * Generates a new swipe as a continuation of the given prompt, when user selects
 * an alternative token or rerolls from a prefix.
 * @param prompt
 */
// @ts-expect-error TS(7006) FIXME: Parameter 'prompt' implicitly has an 'any' type.
function addGeneration(prompt) {
    const messageId = chat.length - 1;
    const triggerSwipe = () => {
        const swipes = document.querySelectorAll('.swipe_right');
        const lastSwipe = swipes[swipes.length - 1];
        if (lastSwipe instanceof HTMLElement) {
            lastSwipe.click();
        }
    };
    if (prompt && prompt.length > 0) {
        createSwipe(messageId, prompt);
        triggerSwipe();
        void Generate('continue');
    } else {
        triggerSwipe();
    }
}

/**
 * onToggleLogprobsPanel is called when the user performs an action that toggles
 * the logprobs view, such as clicking the Token Probabilities menu item or the
 * close button.
 */
function onToggleLogprobsPanel() {
    const logprobsViewer = document.getElementById('logprobsViewer');
    if (!logprobsViewer) {
        return;
    }

    // largely copied from CFGScale toggle
    if (getComputedStyle(logprobsViewer).display === 'none') {
        logprobsViewer.classList.add('resizing');
        logprobsViewer.style.display = 'flex';
        logprobsViewer.style.opacity = '0';
        renderAlternativeTokensView();
        const anim = logprobsViewer.animate([
            { opacity: '0' },
            { opacity: '1' },
        ], {
            duration: animation_duration,
            easing: 'ease',
        });
        anim.onfinish = async function () {
            await delay(50);
            logprobsViewer.classList.remove('resizing');
        };
    } else {
        logprobsViewer.classList.add('resizing');
        const anim = logprobsViewer.animate([
            { opacity: getComputedStyle(logprobsViewer).opacity },
            { opacity: '0' },
        ], {
            duration: animation_duration,
            easing: 'ease',
        });
        anim.onfinish = async function () {
            await delay(50);
            logprobsViewer.classList.remove('resizing');
        };
        setTimeout(function () {
            logprobsViewer.style.display = 'none';
        }, animation_duration);
    }
}

/**
 * Appends a new swipe to the target chat message with the given text.
 * @param {number} messageId - target chat message ID
 * @param {string} prompt - initial prompt text which will be continued
 */
// @ts-expect-error TS(7006) FIXME: Parameter 'messageId' implicitly has an 'any' type... Remove this comment to see the full error message
function createSwipe(messageId, prompt) {
    // need to call `cleanUpMessage` on our new prompt, because we were working
    // with raw model output and our new prompt is missing trimming/macro replacements
    let cleanedPrompt = cleanUpMessage({
        getMessage: prompt,
        isImpersonate: false,
        isContinue: false,
        displayIncompleteSentences: true,
    });

    const msg = chat[messageId];

    const reasoningPrefix = substituteParamsExtended(power_user.reasoning.prefix);
    const reasoningSuffix = substituteParamsExtended(power_user.reasoning.suffix);
    const isReasoningAutoParsed = power_user.reasoning.auto_parse;
    // @ts-expect-error TS(2532) FIXME: Object is possibly 'undefined'.
    const msgHasParsedReasoning = msg.extra?.reasoning?.length > 0;
    let shouldRerollReasoning = false;

    //if we have pre-existing reasoning and are currently autoparsing
    if (isReasoningAutoParsed && msgHasParsedReasoning) {
        console.debug('saw autoparse on with reasoning in message');
        //but the reroll prompt does not include the end of reasoning
        // @ts-expect-error TS(2571) FIXME: Object is of type 'unknown'.
        if (cleanedPrompt.includes(reasoningPrefix) && !cleanedPrompt.includes(reasoningSuffix)) {
            //we need to send the results to the reasoning block
            //this will involve the ReasoningHandler from reasoning.js
            console.debug('..with start tag but no end tag... reroll reasoning');
            shouldRerollReasoning = true;
        }

        // @ts-expect-error TS(2571) FIXME: Object is of type 'unknown'.
        const hasReasoningPrefix = cleanedPrompt.includes(reasoningPrefix);
        // @ts-expect-error TS(2571) FIXME: Object is of type 'unknown'.
        const hasReasoningSuffix = cleanedPrompt.includes(reasoningSuffix);

        //..with both the start and end think tags
        //OR
        //..with only the end think tag (implying prefilled think start)
        if (hasReasoningPrefix && hasReasoningSuffix) {
            //we need to send the results to the response block without reasoning attached
            console.debug('...incl. end tag...rerolling response');
            // @ts-expect-error TS(2571) FIXME: Object is of type 'unknown'.
            const endOfThink = cleanedPrompt.indexOf(reasoningSuffix) + reasoningSuffix.length;
            // @ts-expect-error TS(2571) FIXME: Object is of type 'unknown'.
            cleanedPrompt = cleanedPrompt.substring(endOfThink);
        }

        //if cleanedprompt includes the think prefix, but no suffix..
        if (hasReasoningPrefix && !hasReasoningSuffix) {
            console.debug('..no end tag...rerolling reasoning, so removing prefix');
            // @ts-expect-error TS(2571) FIXME: Object is of type 'unknown'.
            cleanedPrompt = cleanedPrompt.replace(reasoningPrefix, '');
        }
    }

    console.debug('cleanedPrompt: ', cleanedPrompt);

    /** @type {SwipeInfo} */
    const newSwipeInfo = {
        // @ts-expect-error TS(2532) FIXME: Object is possibly 'undefined'.
        send_date: msg.send_date,
        // @ts-expect-error TS(2532) FIXME: Object is possibly 'undefined'.
        gen_started: msg.gen_started,
        // @ts-expect-error TS(2532) FIXME: Object is possibly 'undefined'.
        gen_finished: msg.gen_finished,
        // @ts-expect-error TS(2532) FIXME: Object is possibly 'undefined'.
        extra: { ...structuredClone(msg.extra), from_logprobs: new Date().getTime() },
    };

    // @ts-expect-error TS(2532) FIXME: Object is possibly 'undefined'.
    msg.swipes = msg.swipes || [];
    // @ts-expect-error TS(2532) FIXME: Object is possibly 'undefined'.
    msg.swipe_info = msg.swipe_info || [];

    // Add our new swipe, then make sure the active swipe is the one just before
    // it. The call to `swipe_right` in addGeneration() will switch to it immediately.

    //if we determined that we need to reroll from reasoning
    if (shouldRerollReasoning) {
        //cleaned prompt goes into reasoning
        newSwipeInfo.extra.reasoning = cleanedPrompt;
        //mes_text becomes empty, causing the reasoning handler to parse the reasoning first
        // @ts-expect-error TS(2532) FIXME: Object is possibly 'undefined'.
        msg.swipes.push('');
    } else {
        //otherwise just add the cleaned prompt to the message and continue
        // @ts-expect-error TS(2532) FIXME: Object is possibly 'undefined'.
        msg.swipes.push(cleanedPrompt);
    }

    // @ts-expect-error TS(2532) FIXME: Object is possibly 'undefined'.
    msg.swipe_info.push(newSwipeInfo);
    // @ts-expect-error TS(2532) FIXME: Object is possibly 'undefined'.
    msg.swipe_id = Math.max(0, msg.swipes.length - 2);
}

/**
 * toVisibleWhitespace receives input text and replaces spaces with &middot; and
 * newlines with ↵.
 * @param {string} input
 * @returns {string}
 */
// @ts-expect-error TS(7006) FIXME: Parameter 'input' implicitly has an 'any' type.
function toVisibleWhitespace(input) {
    return input.replace(/ /g, '·').replace(/[▁Ġ]/g, '·').replace(/[Ċ\n]/g, '↵');
}

/**
 * withVirtualWhitespace inserts line breaks and a zero-width space before and
 * after the span node if its token begins or ends with whitespace in order to
 * allow text to wrap despite whitespace characters being replaced with a dot.
 * @param {string} text - token text being evaluated for whitespace
 * @param {Node} span - target span node to be wrapped
 * @returns {Node[]} - array of nodes to be appended to the parent element
 */
// @ts-expect-error TS(7006) FIXME: Parameter 'text' implicitly has an 'any' type.
function withVirtualWhitespace(text, span) {
    /** @type {Node[]} */
    const result = [span];
    if (text.match(/^\s/)) {
        result.unshift(document.createTextNode('\u200b'));
    }
    if (text.match(/\s$/)) {
        result.push(document.createTextNode('\u200b'));
    }
    if (text.match(/^[▁Ġ]/)) {
        result.unshift(document.createTextNode('\u200b'));
    }
    // line breaks are trickier. we don't currently handle consecutive line
    // breaks or line breaks occuring in between non-whitespace characters, but
    // tokenizers generally don't produce those anyway.

    // matches leading line break, at least one character, and trailing line break
    if (text.match(/^\n(?:.|\n)+\n$/)) {
        result.unshift(document.createElement('br'));
        result.push(document.createElement('br'));
    } else if (text.match(/^\n/)) {
        result.unshift(document.createElement('br'));
    } else if (text.match(/\n$/)) {
        result.push(document.createElement('br'));
    }
    return result;
}

/**
 * Receives the top logprobs for each token in a message and associates it with the active message.
 *
 * Ensure the active message has been updated and rendered before calling this function
 * or the logprobs data will be saved to the wrong message.
 *
 * Callers:
 * - Generate:onSuccess via saveLogprobsForActiveMessage, for non-streaming text completion
 * - StreamingProcessor:onFinishStreaming, for streaming text completion
 * - sendOpenAIRequest, for non-streaming chat completion
 * @param {TokenLogprobs[]} logprobs - array of logprobs data for each token
 * @param {string | null} continueFrom  - for 'continue' generations, the prompt
 */
// @ts-expect-error TS(7006) FIXME: Parameter 'logprobs' implicitly has an 'any' type.
export function saveLogprobsForActiveMessage(logprobs, continueFrom) {
    if (!logprobs) {
        // non-streaming APIs could return null data
        return;
    }

    // NovelAI only returns token IDs in logprobs data; convert to text tokens in-place
    if (getGeneratingApi() === 'novel') {
        convertTokenIdLogprobsToText(logprobs);
    }

    const msgId = chat.length - 1;
    /** @type {MessageLogprobData} */
    const data = {
        created: new Date().getTime(),
        api: getGeneratingApi(),
        messageId: msgId,
        // @ts-expect-error TS(2532) FIXME: Object is possibly 'undefined'.
        swipeId: chat[msgId].swipe_id,
        messageLogprobs: logprobs,
        continueFrom,
        hash: getMessageHash(chat[msgId]),
    };

    state.messageLogprobs.set(data.hash, data);

    // Clean up old logprobs data
    const oldLogprobs = Array.from(state.messageLogprobs.values())
        .sort((a, b) => b.created - a.created)
        .slice(MAX_MESSAGE_LOGPROBS);
    for (const oldData of oldLogprobs) {
        state.messageLogprobs.delete(oldData.hash);
    }
}

/**
 *
 * @param message
 */
// @ts-expect-error TS(7006) FIXME: Parameter 'message' implicitly has an 'any' type.
function getMessageHash(message) {
    // We don't use the swipe ID as a hash component because it's not stable,
    // deleting a swipe will change the ID of all subsequent swipes.
    const hashParams = {
        name: message.name,
        // @ts-expect-error TS(2345) FIXME: Argument of type 'any' is not assignable to parame... Remove this comment to see the full error message
        mid: chat.indexOf(message),
        text: message.mes,
    };
    return getStringHash(JSON.stringify(hashParams));
}

/**
 * getActiveMessageLogprobData returns the logprobs data for the active chat
 * message.
 * @returns {MessageLogprobData|null}
 */
function getActiveMessageLogprobData() {
    if (chat.length === 0) {
        return null;
    }

    const hash = getMessageHash(chat[chat.length - 1]);
    return state.messageLogprobs.get(hash) || null;
}


/**
 * convertLogprobTokenIdsToText replaces token IDs in logprobs data with text tokens,
 * for APIs that return token IDs instead of text tokens, to wit: NovelAI.
 * @param {TokenLogprobs[]} input - logprobs data with numeric token IDs
 */
// @ts-expect-error TS(7006) FIXME: Parameter 'input' implicitly has an 'any' type.
function convertTokenIdLogprobsToText(input) {
    const api = getGeneratingApi();
    if (api !== 'novel') {
        // should have been checked by the caller
        throw new Error('convertTokenIdLogprobsToText should only be called for NovelAI');
    }

    const tokenizerId = getTokenizerBestMatch(api);

    /** @type {any[]} Flatten unique token IDs across all logprobs */
    // @ts-expect-error TS(7006) FIXME: Parameter 'logprobs' implicitly has an 'any' type.
    const tokenIds = Array.from(new Set(input.flatMap(logprobs =>
        // @ts-expect-error TS(7031) FIXME: Binding element 'token' implicitly has an 'any' ty... Remove this comment to see the full error message
        logprobs.topLogprobs.map(([token]) => token).concat(logprobs.token),
    )));

    // Submit token IDs to tokenizer to get token text, then build ID->text map
    // noinspection JSCheckFunctionSignatures - mutates input in-place
    const { chunks } = decodeTextTokens(tokenizerId, tokenIds);
    const tokenIdText = new Map(tokenIds.map((id, i) => [id, chunks[i]]));

    // Fixup logprobs data with token text
    // @ts-expect-error TS(7006) FIXME: Parameter 'logprobs' implicitly has an 'any' type.
    input.forEach(logprobs => {
        logprobs.token = tokenIdText.get(logprobs.token);
        // @ts-expect-error TS(7031) FIXME: Binding element 'token' implicitly has an 'any' ty... Remove this comment to see the full error message
        logprobs.topLogprobs = logprobs.topLogprobs.map(([token, logprob]) =>
            [tokenIdText.get(token), logprob],
        );
    });
}

/**
 *
 */
export function initLogprobs() {
    if (REROLL_BUTTON) REROLL_BUTTON.style.display = 'none';
    const debouncedRender = debounce(renderAlternativeTokensView);
    const closeBtn = document.getElementById('logprobsViewerClose');
    if (closeBtn) closeBtn.addEventListener('click', onToggleLogprobsPanel);
    const toggleBtn = document.getElementById('option_toggle_logprobs');
    if (toggleBtn) toggleBtn.addEventListener('click', onToggleLogprobsPanel);
    eventSource.on(event_types.CHAT_CHANGED, debouncedRender);
    eventSource.on(event_types.CHARACTER_MESSAGE_RENDERED, debouncedRender);
    eventSource.on(event_types.IMPERSONATE_READY, debouncedRender);
    eventSource.on(event_types.MESSAGE_DELETED, debouncedRender);
    eventSource.on(event_types.MESSAGE_EDITED, debouncedRender);
    eventSource.on(event_types.MESSAGE_SWIPED, debouncedRender);
}
